### ISSUE TITLE
Deciding upload mechanisim and network problems

### ISSUE THREAD

**Issue by BaturayOnural** [kasirgalabs/Tilki#5]
On Windows, video size is currently lowered to ~35 mb . Unfortunately Ubuntu has still 700-800 mb average size. I am talking with the distributors of the CaptureDesktop(JxCapture) to solve Ubuntu issue.
We should decide which method we will be using;
-Should we send the code, before the video?
-Should we send all the files together ?
*_Choosing 1st option brings another problem with it(Checksum).
*_We also certainly try the network system before exam.

**Comment by RootG** [comment]
Since the user is not interested to verify the video is uploaded successfully, sending the codes before the video in a zip file then receiving the checksum for the codes will be a more better approach. By taking this approach user will be able to verify the integrity of he's code by the checksum without waiting to send video file. In case of a slow network connection we may let the user to skip the video upload.

**Comment by BaturayOnural** [comment]
Since we don't have much time for the 1st release, it should be done about 4-5 days max. And we should discuss about the network system. Some classes have serious problems about connection. It may not be possible to send the contents without a wired connection.
